#!/usr/bin/env python3
"""Generates src/demo_log_data.cpp from a real candump log in data/logs/, so
the demo build (pio run -e demo, DEMO_FAKE_DATA) replays an actual drive
through the real can_decoder.cpp bit-math instead of a synthetic sweep.

Only the ~8 CAN IDs can_decoder.cpp actually decodes are kept (the rest of
the ~100 IDs on the bus are irrelevant to this UI and would just bloat the
embedded array). Timestamps become milliseconds relative to the first kept
frame, monotonic, for the demo replay loop in can_decoder.cpp to step
through.

Usage: python3 scripts/gen_demo_log.py [session_log_path]
Defaults to data/logs/session_0047.log (440s, includes the full P/R/N/D/B
gear cycle and both EV and ICE driving -- see docs/signal_findings.md's
Addendum for why this session is the more complete one of the two).
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tools"))
from parse_log import parse  # noqa: E402

DEFAULT_LOG = REPO_ROOT / "data" / "logs" / "session_0047.log"
OUTPUT = Path(__file__).resolve().parents[1] / "src" / "demo_log_data.cpp"

# Must match the IDs can_decoder.cpp's decodeIntoState() switches on.
RELEVANT_IDS = {0x0B4, 0x1C4, 0x127, 0x245, 0x498, 0x247, 0x4A7, 0x442}

# The UI only syncs at ~30Hz (UI_SYNC_INTERVAL_MS), so the ~33-47Hz native
# rate of some of these signals (SPEED/RPM/GEAR/GAS_PEDAL/HSI) is more
# resolution than will ever be visible -- decimate those down to roughly
# this rate per-ID to keep the embedded array a reasonable size (cuts it by
# ~2-3x) without any visible loss of smoothness. Low-rate IDs (~1.5Hz:
# EV/battery/temperature) are left untouched.
TARGET_HZ = 15.0


def main():
    log_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_LOG
    frames = parse(str(log_path))
    relevant = [(ts, can_id, data) for ts, can_id, data in frames if can_id in RELEVANT_IDS]
    if not relevant:
        sys.exit(f"no relevant frames found in {log_path}")

    duration_s = relevant[-1][0] - relevant[0][0]
    counts = {}
    for _, can_id, _ in relevant:
        counts[can_id] = counts.get(can_id, 0) + 1
    strides = {}
    for can_id, n in counts.items():
        native_hz = n / duration_s
        strides[can_id] = max(1, round(native_hz / TARGET_HZ))

    seen = {}
    kept = []
    for ts, can_id, data in relevant:
        seen[can_id] = seen.get(can_id, 0) + 1
        if (seen[can_id] - 1) % strides[can_id] == 0:
            kept.append((ts, can_id, data))

    t0 = kept[0][0]
    lines = []
    lines.append("// GENERATED by scripts/gen_demo_log.py -- do not hand-edit.")
    lines.append(f"// Source: {log_path.relative_to(REPO_ROOT)}, {len(kept)} frames"
                  f" ({(kept[-1][0] - t0):.1f}s), filtered to the IDs can_decoder.cpp decodes.")
    lines.append("#ifdef DEMO_FAKE_DATA")
    lines.append('#include "demo_log_data.h"')
    lines.append("")
    lines.append("const DemoLogFrame kDemoLog[] = {")
    for ts, can_id, data in kept:
        t_ms = round((ts - t0) * 1000)
        data_padded = data.ljust(8, b"\x00")
        byte_list = ", ".join(f"0x{b:02X}" for b in data_padded)
        lines.append(f"    {{{t_ms}, 0x{can_id:03X}, {len(data)}, {{{byte_list}}}}},")
    lines.append("};")
    lines.append("")
    lines.append("const size_t kDemoLogCount = sizeof(kDemoLog) / sizeof(kDemoLog[0]);")
    lines.append(f"const uint32_t kDemoLogDurationMs = {round((kept[-1][0] - t0) * 1000)};")
    lines.append("#endif // DEMO_FAKE_DATA")
    lines.append("")

    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT} ({len(kept)} frames, {(kept[-1][0] - t0):.1f}s)")


if __name__ == "__main__":
    main()
