#pragma once

// Generated by scripts/gen_demo_log.py from a real candump log (see that
// script for which one and why). Only built/used in the demo target
// (DEMO_FAKE_DATA) -- see can_decoder.cpp's demo replay branch.

#include <cstddef>
#include <cstdint>

struct DemoLogFrame {
    uint32_t t_ms;   // relative to the first kept frame, monotonic
    uint16_t id;
    uint8_t dlc;
    uint8_t data[8];
};

extern const DemoLogFrame kDemoLog[];
extern const size_t kDemoLogCount;
extern const uint32_t kDemoLogDurationMs;
