#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Generated by scripts/gen_fonts.sh from fonts_src/DIN_Next_LT_Pro_Bold_Synthetic.otf
// (see scripts/synth_bold.py -- only the Regular weight was available, this
// is a FontForge-emboldened synthetic Bold). One file per pixel size, each
// subsetted to only the glyphs actually used, to keep flash usage down.

extern const lv_font_t dinnext_120_speed; // speed number
extern const lv_font_t dinnext_40_gear;   // gear letter (P/R/N/D/B)
extern const lv_font_t dinnext_30_units;  // "KM/H" unit label
extern const lv_font_t dinnext_26_battery; // HV battery SOC numeric
extern const lv_font_t dinnext_28_ev;     // "EV" label
extern const lv_font_t dinnext_26_rpm;    // RPM label+value row (centered group, below speed); also left-slot temp/clock
extern const lv_font_t dinnext_14_chgpwr; // "CHG"/"PWR" bar labels
extern const lv_font_t dinnext_13_pct;    // "%" suffix
extern const lv_font_t dinnext_24_label;  // energy-flow node labels (full A-Z uppercase)
extern const lv_font_t dinnext_28_stat;   // efficiency-screen headline + tile values (full A-Z uppercase)
extern const lv_font_t dinnext_40_accel_time;  // 0-50/0-100 timer: elapsed seconds -- same size as dinnext_40_gear, replaces the gear letter while shown
extern const lv_font_t dinnext_40_accel_label; // 0-50/0-100 timer: "0-50"/"0-100" threshold caption, below the seconds

#ifdef __cplusplus
}
#endif
